image: gcc

stages:
  - prepare
  - build
  - test

prepare_packages:
  stage: prepare
  script:
    - apt-get update --yes
    - apt-get install --yes cmake clang libasound2-dev libglu1-mesa-dev freeglut3-dev libglfw3-dev libgles2-mesa-dev

build_ap:
  stage: build
  script:
    - cd antarctica_pyramids
    - cmake .
    - make all
    - cmake -DCMAKE_BUILD_TYPE=Debug .
    - make all
    - cd ..


build_wizard:
  stage: build
  script:
    - cd wizard
    - cmake .
    - make all
    - cmake -DCMAKE_BUILD_TYPE=Debug .
    - make all
    - cd ..

build_filetest:
  stage: build
  script:
    - cd filetest
    - cmake .
    - make all
    - cmake -DCMAKE_BUILD_TYPE=Debug .
    - make all
    - cd ..

build_tests:
  stage: build
  script:
    - cd tests
    - cmake .
    - make all
    - ./tests
    - cmake -DCMAKE_BUILD_TYPE=Debug .
    - make all
    - cd ..

run_tests:
  stage: test
  script:
    - cd tests
    - cmake .
    - make all
    - ./tests
    - cmake -DCMAKE_BUILD_TYPE=Debug .
    - make all
    - ./tests
    - cd ..

create_project:
  stage: test
  script:
    - cd wizard
    - ./wizard create test_project
    - cd ../../test_project
    - cmake .
    - make all
    - ce ..
